name: bioinfo
channels:
  - bioconda
  - conda-forge
  - https://s3.cl5.du.cesnet.cz/f463c41e_8ad6_4e8e_a0ad_4b3370c11a04:conda-forge-s3chnl
  - https://s3.cl5.du.cesnet.cz/f463c41e_8ad6_4e8e_a0ad_4b3370c11a04:bioconda-s3chnl
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - bcftools=1.22
  - beautifulsoup4=4.13.5
  - bedtools=2.31.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - double-conversion=3.3.1
  - emboss=6.6.0
  - filelock=3.19.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.2
  - freetype=2.14.0
  - gdown=5.2.0
  - graphite2=1.3.14
  - gsl=2.7
  - h2=4.3.0
  - harfbuzz=11.4.5
  - hpack=4.1.0
  - htslib=1.22.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - k8=1.2
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.0
  - libfreetype6=2.14.0
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgd=2.3.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libharu=2.4.5
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopenssl-static=3.5.3
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - mariadb-connector-c=3.4.7
  - markdown-it-py=4.0.0
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - mdurl=0.1.2
  - minimap2=2.30
  - munkres=1.1.4
  - mysql-connector-c=6.1.11
  - ncurses=6.5
  - numpy=2.3.3
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.3
  - packaging=25.0
  - paf2chain=0.1.1
  - pandas=2.3.2
  - pathlib=1.0.1
  - pcre2=10.45
  - perl=5.32.1
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pysam=0.23.3
  - pyside6=6.9.2
  - pysocks=1.7.1
  - python=3.13.7
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.9.2
  - readline=8.2
  - requests=2.32.5
  - rich=14.2.0
  - samtools=1.22.1
  - scipy=1.16.1
  - six=1.17.0
  - soupsieve=2.8
  - sysroot_linux-64=2.34
  - tk=8.6.13
  - tornado=6.5.2
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucsc-liftover=482
  - urllib3=2.5.0
  - wayland=1.24.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zstandard=0.24.0
  - zstd=1.5.7
